---
title: "Assignment 1: Introduction"
author: "David Amanfu"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: 
I have looked through Grant McDermott's EC607 from the University of Oregon, found here https://github.com/uo-ec607, where I was first exposed to some of what is going on in R. That is about the most formal R experience I've had, and I only barely got through the first quarter of the course before the Fall semester began. Otherwise, I've done a lot of excel and a decent amount of Python using Calliope https://calliope.readthedocs.io/en/stable/ and a ton of 8760 data from my time as a sustainability analyst/consultant for a structural engineering firm.  I feel very comfortable coding and troubleshooting, I just don't know R too well. But feels like it'll be easy to get after. I've also done a bit of stata in PubPol 813 this past fall semester, so I feel moderately prepared for the types of analyses we might be doing.

2. Are there any components of the course about which you feel confident?

> Answer:
Coding! Data interpretation!

3. Are there any components of the course about which you feel apprehensive?

> Answer: 
Coding in R! Data cleaning!


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/DavidAmanfu/Environmental_Data_Analytics_2022


